### ISSUE TITLE
Judges assignments

### ISSUE THREAD

**Issue by timparenti** [cmukgb/ctfws-timer-page#11]
Need from the field, S19:

A place to store judge assignments to the server, and conveniently copy/paste a plaintext version of a given game's judges into the group chat _du jour_.

**Comment by timparenti** [comment]
Something vaguely resembling [this stylized template](https://docs.google.com/spreadsheets/d/1NS0XxWDWAwE5mUkY2hiLm_yn6Vw_DJo1Mq1QPm8NiPg/) which has been used of-late.

Desirable resulting plaintext could be something like:
> **GAME n:**
> HEAD: $name
> DH JAIL: $name
> DH ROAM: $name, $name
> WeH JAIL: $name
> WeH ROAM: $name, $name
> ON CALL: $name, $name…

**Comment by michaelfelixmurphy** [comment]
Finished and deployed!
http://timer.cmukgb.org/judge/#judges
