### ISSUE TITLE
Make stale heartbeats clearer

### ISSUE THREAD

**Issue by timparenti** [cmukgb/ctfws-timer-page#13]
Somewhat related/interleaved with cmukgb/ctfws-timer-iot#7 to get at optimal behavior.

The devices tab should parse out just how long it's been since the beat was received, and ideally show the time interval since then.  If it's been above some threshold (~1.5× ?), colorize the heartbeat line to draw attention to it (perhaps yellow?).  Maybe some further color gradation if it can be "stale" but not "dead" for a significant time.  If it's "dead", perhaps red.

Bonus points if the tab itself can also show colored badges with counts as appropriate when there's something amiss, so that any "error" states can be visible even if the judge is working on another tab of the Judges' panel at the time.

**Comment by michaelfelixmurphy** [comment]
I believe I have all of this implemented locally. What should the threshold in seconds be for turning a row yellow? I imagine it depends on the frequency of the heartbeats, which I don't know.

**Comment by nwf** [comment]
https://github.com/cmukgb/ctfws-timer-iot/issues/7 suggests that the current heartbeat of 60 seconds is too slow and that we use something like 20 instead.  That's a relatively easy to do, I just haven't yet, but the web frontend should probably pretend like I have. ;)  We should probably set the "dead" timeout (which is managed by the broker after it sees the device fall offline) to ~120 seconds or so, so if you want an upper bound on your "badness of delay gradient", probably go with something like that.

**Comment by michaelfelixmurphy** [comment]
Ok, I currently have red = the latest message says “dead” and yellow = more than 60 seconds since last beat. Given the beat is every 20 seconds and the auto-death is 120, setting the “warning” threshold to 60 sounds right. (I’m not bothering with a gradient of colors.)

**Comment by nwf** [comment]
OK!  I've been meaning to find some time to wander down the todos, and I'll try to get to this soonish. :)

**Comment by michaelfelixmurphy** [comment]
This is pushed but not deployed. The judges assignments are half implemented, so I need to finish that before deploying.
