### ISSUE TITLE
Option to send a known message at game start

### ISSUE THREAD

**Issue by timparenti** [cmukgb/ctfws-timer-page#7]
Often, a message is sent shortly after "end game" which reiterates that the game is over and encourages players to bring Stuff back to the main room.  In practice, the time between this "end game" and the beginning of the setup period for the next game is rather frenetic, and it is easy to forget to reset this message before the next game is started.

While this is not a problem during the interval itself, if this is not caught before the setup period is started, this means that a confusing "game over"-type message remains the most recently-sent message during portions of the setup phase.

**Proposal:** In the "start game" section of the Judges' game panel, place a default-checked checkbox next to the WeH/DH radio buttons which, when checked, will also cause a known message to be sent to both players and jails.  A suggestion, based on [the image from the writeup](https://www.ietfng.org/nwf/ee/ctfws-iot.html) on @nwf's website, would be `R=Doherty Y=Wean` or `R=Wean Y=Doherty`, as appropriate.

**Comment by michaelfelixmurphy** [comment]
How about a default message of "Setup start! Red is defending Wean. Yellow is defending Doherty."? Or is this too long for the IoT devices? What about that for the players and "R=Wean Y=Doherty" for the jails? I could also do something like "Game N setup start!".

**Comment by nwf** [comment]
The IoT devices will scroll long messages, so should be fine. :)

Maybe derive the "is defending" bits from the territory configuration being set?  It might be a little redundant on the app, which will also display the territory config...  But otherwise that seems like the right kind of default to me.

**Comment by timparenti** [comment]
Yes, @nwf, the idea was to derive the message from the appropriate territory config.

I suppose the player message and jail message need not be the same.  I know it would be three messages in quick succession, but perhaps (if the box remains checked to do this):

* Start game timers
* Player message = e.g., "Red is defending Doherty. Yellow is defending Wean."
* Jail message = e.g., "R=Doherty Y=Wean"

I only worry about including "Setup start!" because these messages, too, are liable to linger for a while after the setup period ends, depending on how attentive to the app the judges are able to be for that round, which just ends up punting the actual problem a bit.

**Comment by michaelfelixmurphy** [comment]
Done in  [7a8afd4](/cmukgb/ctfws-timer-web/commit/7a8afd4aefb5deaf29ba57a8df4643944f64e25c)
